[package]
name = "textli-api"
version = "0.1.0"
authors = ["Florian Marending <florian@marending.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
bcrypt = "0.8"
rand = "0.8"
lazy_static = "1.4.0"
ring = "0.16.19"
warp = "0.3"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "migrate", "uuid", "chrono" ] }

[profile.dev]
split-debuginfo = "unpacked"
