services:
  fieldnotes-db:
    image: postgres:latest
    container_name: fieldnotes-db
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    volumes:
      - fieldnotes-pg:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - fieldnotes_net

  fieldnotes-api:
    image: "ghcr.io/beingflo/fieldnotes-api:1.0"
    container_name: fieldnotes-api
    ports:
      - 5005:5005
    env_file:
      - .env.prod
    depends_on:
      - fieldnotes-db
    restart: unless-stopped
    networks:
      - caddy_net
      - fieldnotes_net

  pg_backup_s3:
    image: "ghcr.io/beingflo/postgres-backup-s3:1.2"
    env_file: ".env.prod.backup"
    networks:
      - fieldnotes_net

networks:
  fieldnotes_net:
    name: "fieldnotes_net"
  caddy_net:
    external: true

volumes:
  fieldnotes-pg:
    name: "fieldnotes-pg"
